name: Azure Packer Terraform Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  packer-build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Packer
      uses: hashicorp/setup-packer@main

    - name: Packer Init
      run: |
        cd packer
        packer init .

    - name: Packer Validate
      run: |
        cd packer
        packer validate -var-file="pakvars.pkrvars.hcl" .

    - name: Packer Build
      run: |
        cd packer
        packer build -var-file="pakvars.pkrvars.hcl" .

  terraform-deploy:
    #needs: packer-build
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Azure Login using OIDC
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: |
        cd terraform
        terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve
      env:
        TF_VAR_ssh_public_key: ${{ secrets.TF_SSH_PUBLIC_KEY }}
